### ISSUE TITLE
Cannot create constraints for IMU Twist messages with less than 2ms delay

### ISSUE THREAD

**Issue by meghdeepj** [locusrobotics/fuse#223]
Board: Nvidia Jetson Nano (Jetpack 4.4)
OS: Ubuntu 18.04
ROS: Melodic

Fuse sounds very promising and I am eager to use it for my AMR navigation stack. I am using fuse to combine data from Wheel odometry and IMU readings. IMU data is coming from Intel D435i via Madgwick Filter.
My launch file and `smoother.yaml` file is as follows:
 
 ```
<node name="smoother" pkg="fuse_optimizers" type="fixed_lag_smoother_node" output="screen">
        <rosparam command="load" file="$(find loc_mod)/params/fuse_imu.yaml" subst_value="true"/>
```
```
#Fixed-lag smoother configuration
optimization_frequency: 10  # The best-effort frequency (in Hz) of the optimization loop. This means that the optimizer will run every 0.1s and trigger all of the publishers when it is done
lag_duration: 0.5  # The size of the fixed-lag window, in seconds. The larger the window, the more variables will be inside the optimizer at any given time, which affects CPU usage.

# Define the set of motion model plugins to load
# Currently fuse only includes a 2D motion model. This is roughly equivalent to the robot_localization state, including the linear and angular position, the linear and angular velocity, and the linear acceleration. A turtlebot is a 2D robot, so this is fine.
# Multiple motion models can be loaded, and each sensor defines which set of motion models are used. We only have one motion model currently, and all sensors should use it.
motion_models:
  unicycle_motion_model:
    type: fuse_models::Unicycle2D

# Next define the set of sensor plugins to load
# You naturally want an IMU sensor and an Odometry sensor
# Additionally, you may want an "ignition" sensor. Ignition sensors tell the optimizer when to start running and what the initial state should be. fuse ships with one ignition sensor that initializes the Unicycle2D state variables.
sensor_models:
  ignition_sensor:
    type: fuse_models::Unicycle2DIgnition
    motion_models: [unicycle_motion_model]
    ignition: true
  odometry_sensor:
    type: fuse_models::Odometry2D
    motion_models: [unicycle_motion_model]
  imu_sensor:
    type: fuse_models::Imu2D
    motion_models: [unicycle_motion_model]

# And finally, define the set of publishers. fuse_models includes a robot_localization like publisher that publishes the latest state to the odom and tf topics.
publishers:
  odom_publisher:
    type: fuse_models::Odometry2DPublisher

# That is it for the optimizer itself, but each plugin has its own set of configuration. That configuration is specified in a sub-namespace of the plugin's name. E.g. ignition_sensor, odometry_sensor, imu_sensor
# These parameters are not strictly backwards-compatible with robot_localization configuration, but basically all of the same functionality exists.
unicycle_motion_model:
  buffer_length: 1.0  # How long to keep a local history. This should be at least as long as the smoother lag
  process_noise_diagonal: [0.001, 0.001, 0.001, 0.2, 0.2, 0.2, 0.15, 0.001]  # These are in order {x, y, yaw, vx, vy, vyaw, ax, ay}. And note these are variances. The numerical values should be adjusted to the platform.

ignition_sensor:
  publish_on_startup: true  # Just start immediately. If false, it waits for a service to send it initial state values
  initial_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # The same order as the process noise above
  initial_sigma: [0.000001, 0.000001, 0.000001, 10.0, 10.0, 10.0, 1.0, 0.000001]   # The same order as the process noise above. Note these are standard deviations. The numerical values should be adjusted to the platform.

odometry_sensor:
  topic: /odom/wheel
  twist_target_frame: base_link
  linear_velocity_dimensions: ['x', 'y']
  angular_velocity_dimensions: ['yaw']
  # The above configuration only uses the odometry velocity information. There are several options for using the odometry pose information as well.

imu_sensor:
  topic: /imu/data
  angular_velocity_dimensions: ['yaw']
  linear_acceleration_dimensions: ['x']
  twist_target_frame: base_link
  # The above configuration only uses the yaw velocity of the IMU measurement. Depending on the IMU data available, additional measurement dimensions can be added

odom_publisher:
  topic: odom
  base_link_frame_id: base_link
  odom_frame_id: odom
  map_frame_id: map
  world_frame_id: odom
  publish_tf: true
  # The odometry publisher also has several configuration modes, again very similar to the robot_localization package. The exact settings will depend on whether you are trying to fuse multiple dead reckoning sensors to make a better "odom" source, or if you are fusing in global state data and want to publish the map->odom transform.

```
The delay in the IMU time stamp is hardly +-0.001~0.002 ms and I am getting the following error on running the lag_smoother.

```
[ERROR] [1612442903.265861936]: Cannot create constraint from twist message with stamp 1612442903.265639067
[ERROR] [1612442903.269917145]: Cannot create constraint from twist message with stamp 1612442903.268141985
[ERROR] [1612442903.270205582]: Cannot create constraint from twist message with stamp 1612442903.270646095
[ERROR] [1612442903.273827301]: Cannot create constraint from twist message with stamp 1612442903.273149014
[ERROR] [1612442903.277885374]: Cannot create constraint from twist message with stamp 1612442903.275653124
[ERROR] [1612442903.278127666]: Cannot create constraint from twist message with stamp 1612442903.278156042
[ERROR] [1612442903.282078759]: Cannot create constraint from twist message with stamp 1612442903.280660152
[ERROR] [1612442903.282325686]: Cannot create constraint from twist message with stamp 1612442903.283163071
[ WARN] [1612442903.282408082]: Optimization exceeded the configured duration by 0.003019425s
[ERROR] [1612442903.285876728]: Cannot create constraint from twist message with stamp 1612442903.285665989
[ERROR] [1612442903.289928499]: Cannot create constraint from twist message with stamp 1612442903.288170099
[ERROR] [1612442903.290246988]: Cannot create constraint from twist message with stamp 1612442903.290674210
```
Thanks for your help.
